import {Game,BIOMES,W,H} from './engine.js';
const $=id=>document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let clock=0,last=0,accumulator=0,toastTimer,audio,sound=false;
const bellSVG='<svg viewBox="0 0 20 24" fill="none" aria-hidden="true"><path d="M7 4a3 3 0 0 1 6 0M4 10a6 6 0 0 1 12 0v5l2 3H2l2-3z" stroke="currentColor" stroke-width="1.5"/><path d="M8 21h4" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>';
function tone(kind){if(!sound||!audio)return;const osc=audio.createOscillator(),gain=audio.createGain();const pitches={flip:160,hit:320,collect:740,portal:110,spirit:880,bell:1046,lost:100};osc.frequency.setValueAtTime(pitches[kind]||480,audio.currentTime);osc.frequency.exponentialRampToValueAtTime((pitches[kind]||480)*1.4,audio.currentTime+.12);osc.type=kind==='flip'?'triangle':'sine';gain.gain.setValueAtTime(.045,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.25);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.26);}
function notify(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3400);}
function overlay(eyebrow,title,text,button){$('overlayEyebrow').textContent=eyebrow;$('overlayTitle').innerHTML=title;$('overlayText').textContent=text;$('playButton').innerHTML=button+' <span>↗</span>';$('overlayHint').textContent='SEVEN LIVES. INFINITE WORLDS. ONE VERY GOOD FRIEND.';$('overlay').hidden=false;}
const game=new Game(e=>{tone(e.type);if(e.text&&!['gameover'].includes(e.type))notify(e.text);if(e.type==='gameover')overlay('YOUR BELLS HAVE FALLEN SILENT','A little rest.<br>Then a little further.','Your biome checkpoint is safe. Your friend is still waiting.','Return to checkpoint');if(e.type==='summit')overlay('THE END OF THIS WORLD','That wasn’t<br>the last universe.','A familiar bark comes from the other side. Somewhere, your dog is still calling.','Follow the bark');});
window.meowltiverse=game;
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);}resize();window.addEventListener('resize',resize);
function circle(x,y,r,fill,stroke,width=1){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}}
function line(x,y,ex,ey,color,width=1){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(ex,ey);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function star(x,y,r,color){ctx.save();ctx.translate(x,y);ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4-Math.PI/2,rad=i%2?r*.3:r;ctx.lineTo(Math.cos(a)*rad,Math.sin(a)*rad);}ctx.closePath();ctx.fillStyle=color;ctx.fill();ctx.restore();}
function paw(x,y,size,color){ctx.save();ctx.translate(x,y);ctx.rotate(-.2);ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(0,3*size,4*size,3*size,0,0,7);ctx.fill();for(let i=0;i<3;i++)circle((i-1)*3.8*size,-2*size-Math.sin(i*Math.PI/2)*2*size,1.7*size,color);ctx.restore();}
function cat(x,y,r,evil=false){ctx.save();ctx.translate(x,y);ctx.shadowBlur=evil?14:20;ctx.shadowColor=evil?'#e679d7':'#aeffdc';const grad=ctx.createRadialGradient(-r*.4,-r*.5,1,0,0,r);grad.addColorStop(0,evil?'#bc75cb':'#effff5');grad.addColorStop(.55,evil?'#563263':(game.room?.kind==='tide'?'#7bdef0':'#b4ead6'));grad.addColorStop(1,evil?'#2c173b':'#6b9eae');ctx.beginPath();ctx.moveTo(-r*.8,-r*.25);ctx.lineTo(-r*.9,-r*1.1);ctx.lineTo(-r*.28,-r*.8);ctx.quadraticCurveTo(0,-r,r*.32,-r*.8);ctx.lineTo(r*.9,-r*1.1);ctx.lineTo(r*.8,-r*.25);ctx.arc(0,0,r,-.25,Math.PI+.25);ctx.closePath();ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle=evil?'#e89cde':'#d5ffe9';ctx.lineWidth=1.2;ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle=evil?'#ffb7db':'#263e47';ctx.lineWidth=1.7;ctx.lineCap='round';for(const sign of [-1,1]){ctx.beginPath();ctx.moveTo(sign*r*.26-r*.13,-r*.12);ctx.lineTo(sign*r*.26+r*.13,-r*.12+(evil?sign*2:0));ctx.stroke();}ctx.beginPath();ctx.moveTo(-2,r*.25);ctx.quadraticCurveTo(0,r*.4,2,r*.25);ctx.stroke();if(!evil){circle(0,r+2,2.5,'#f4d189');line(-r*.68,r*.2,-r*.45,r*.25,'#598b89');line(r*.45,r*.25,r*.68,r*.2,'#598b89');}ctx.restore();}
function portal(x,y,r,kind){ctx.save();ctx.translate(x,y);const color=kind==='tide'?'#83eee4':kind==='exit'?'#f4d28f':'#e5a3ff';ctx.shadowBlur=20;ctx.shadowColor=color;ctx.scale(.82,1.1);circle(0,0,r,'#130d2d',color,2);ctx.shadowBlur=0;for(let i=0;i<4;i++){ctx.save();ctx.rotate(clock*.35+i*.5);ctx.beginPath();ctx.ellipse(0,0,r*(.28+i*.16),r*.8,0,0,7);ctx.strokeStyle=color+(i===3?'70':'35');ctx.lineWidth=1;ctx.stroke();ctx.restore();}star(0,0,10,color);ctx.restore();ctx.fillStyle=color;ctx.font='7px "DM Sans", sans-serif';ctx.textAlign='center';ctx.fillText(kind==='tide'?'LOW GRAVITY':kind==='exit'?'RETURN HOME':'SLOW TIME',x,y+r+24);}
function background(){const bio=BIOMES[game.biome],room=game.room;const bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,room?.kind==='tide'?'#123d45':bio.bg);bg.addColorStop(.6,'#201637');bg.addColorStop(1,'#151025');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);
  // A parallax sky, orbital engravings, and botanical silhouettes.
  for(let i=0;i<80;i++){const x=(Math.sin(i*127.1)*43758.5453%1+1)%1*W,y=((i*97.3+game.camera*.16)%H);const a=.18+.22*Math.sin(clock*.8+i);circle(x,H-y,i%9===0?1.4:.65,`rgba(222,202,255,${a})`);}
  const offset=(game.camera*.23)%850;
  for(let i=-1;i<2;i++){const y=180+i*850+offset;ctx.save();ctx.translate(340,y);ctx.rotate(-.6);ctx.scale(1,.62);for(let j=0;j<6;j++)circle(0,0,65+j*12,null,bio.accent+'13');ctx.restore();circle(334,y,46,'#b18fc509');}
  for(let side=0;side<2;side++){ctx.save();if(side){ctx.translate(W,0);ctx.scale(-1,1);}ctx.fillStyle='#0f0e2377';ctx.beginPath();ctx.moveTo(0,0);for(let y=0;y<=H;y+=20)ctx.lineTo(21+Math.sin(y/65+game.camera/270)*11,y);ctx.lineTo(0,H);ctx.fill();line(18,120,18,H-70,bio.accent+'25');for(let i=0;i<8;i++){let y=(i*115+game.camera*.4)%900-70;ctx.beginPath();ctx.moveTo(10,y+95);ctx.bezierCurveTo(75,y+60,59,y+25,37,y);ctx.bezierCurveTo(32,y+48,14,y+52,10,y+95);ctx.fillStyle=bio.accent+'0c';ctx.fill();ctx.strokeStyle=bio.accent+'23';ctx.stroke();}ctx.restore();}
  if(room?.kind==='tide'){for(let i=0;i<7;i++){ctx.beginPath();for(let y=100;y<700;y+=10)ctx.lineTo(30+i*60+Math.sin(y/90+clock)*15,y);ctx.strokeStyle='#77e9da0e';ctx.stroke();}}
  for(let i=0;i<5;i++){const y=H-((i*165+100-game.camera)%825+825)%825;paw(200+Math.sin(i*2)*55,y,.55,'#e5c98d33');}
}
function draw(){ctx.clearRect(0,0,W,H);ctx.save();if(!reduced&&game.shake>1)ctx.translate(Math.sin(clock*120)*game.shake*.4,Math.cos(clock*95)*game.shake*.3);background();const bio=BIOMES[game.biome],sy=y=>H-(y-game.camera);
  for(const o of game.objects){const y=sy(o.y);if(o.dead||y<-90||y>H+90)continue;let x=o.x;const pulse=1+Math.sin(clock*2+o.y)*.04;
    if(o.type==='bumper'){ctx.save();ctx.translate(x,y);ctx.rotate(clock*.12);circle(0,0,o.r+8,null,bio.accent+'30');for(let i=0;i<6;i++){const a=i*Math.PI/3;circle(Math.cos(a)*(o.r+8),Math.sin(a)*(o.r+8),2,bio.accent+'99');}ctx.shadowBlur=o.cool>0?30:10;ctx.shadowColor=bio.color;circle(0,0,o.r*pulse,bio.color+'16',bio.color+'aa',1.5);circle(0,0,o.r-7,'#231b39',bio.color+'40');star(0,0,10,bio.color);ctx.restore();}
    if(o.type==='star')star(x,y,6+Math.sin(clock*3+o.y), '#f3d592');
    if(o.type==='portal'&&!o.used)portal(x,y,o.r,o.kind);
    if(o.type==='exit')portal(x,y,o.r,'exit');
    if(o.type==='rail'){ctx.save();ctx.lineCap='round';line(x,y,x+o.w,y-o.w*o.slant*.28,'#5a427366',14);line(x,y-2,x+o.w,y-o.w*o.slant*.28-2,bio.accent+'b0',2);for(let i=0;i<3;i++)star(x+15+i*22,y-(15+i*22)*o.slant*.28,3,bio.accent);ctx.restore();}
    if(o.type==='break'){for(let i=0;i<5;i++){ctx.fillStyle='#d9afe522';ctx.strokeStyle='#d9afe560';ctx.beginPath();ctx.roundRect(x+i*28,y-7,24,14,3);ctx.fill();ctx.stroke();}}
    if(o.type==='cat'){x+=Math.sin(game.time*1.3+o.y)*28;circle(x,y,34,null,'#ef90dd22');cat(x,y,21,true);for(let i=0;i<2-o.hits;i++)circle(x-4+i*8,y+32,2.3,'#efb8de');}
    if(o.type==='bell'){circle(x,y,17,null,'#f3d59240');ctx.fillStyle='#f3d592';ctx.font='22px serif';ctx.textAlign='center';ctx.fillText('♧',x,y+7);}
  }
  // Flippers float above an open drain. Their physical tips match this drawing.
  for(let side=0;side<2;side++){const f=game.flipper(side),y=sy(f.y),ey=sy(f.ey);ctx.lineCap='round';ctx.shadowColor=bio.color;ctx.shadowBlur=game.input[side]?24:8;line(f.x,y,f.ex,ey,'#5b7480',21);line(f.x,y-2,f.ex,ey-2,game.input[side]?'#dcffe9':'#b9e8d9',15);ctx.shadowBlur=0;line(f.x,y-5,f.ex,ey-5,'#f0fff688',2);circle(f.x,y,7,'#1c2838', '#ccffea',1);circle(f.x,y,2,bio.color);}
  ctx.textAlign='center';ctx.fillStyle='#b7a2ce40';ctx.font='7px sans-serif';ctx.fillText('✧   KEEP THE LITTLE SPIRIT RISING   ✧',210,H-48);
  const b=game.ball;for(let i=b.trail.length-1;i>=0;i--){const p=b.trail[i];circle(p.x,sy(p.y),b.r*(1-i/24)*.8,bio.color+Math.floor((1-i/23)*35).toString(16).padStart(2,'0'));}cat(b.x,sy(b.y),b.r);
  for(const p of game.particles){ctx.globalAlpha=Math.max(0,p.life);star(p.x,sy(p.y),3*p.life,p.color);}ctx.globalAlpha=1;
  if(game.state==='ready'){portal(92,230,34,'tide');cat(275,192,19);star(342,297,10,'#e8c691');}
  ctx.restore();
}
let lastUI='';function ui(){const signature=[game.lives,Math.floor(game.maxHeight/10),game.score,game.freed,game.biome,game.room?.kind,game.cycle,game.state].join('|');if(signature===lastUI)return;lastUI=signature;$('bells').innerHTML=Array.from({length:7},(_,i)=>`<span class="bell ${i>=game.lives?'lost':''}">${bellSVG}</span>`).join('');$('bells').setAttribute('aria-label',`${game.lives} lives remaining`);$('height').innerHTML=String(Math.floor(game.maxHeight/10)).padStart(4,'0')+'<span> m</span>';$('score').textContent=game.score.toLocaleString();$('spirits').textContent=game.freed;$('biomeName').textContent=game.room?(game.room.kind==='tide'?'LIQUID MOON':'THE HOURS BETWEEN'):BIOMES[game.biome].name;$('biomeDot').style.background=BIOMES[game.biome].color;$('dimensionLabel').textContent='REALITY '+String(game.cycle+1).padStart(3,'0');$('roomRule').hidden=!game.room;$('roomRule').textContent=game.room?.kind==='tide'?'↓ LOW GRAVITY · COLLECT 3 STARDUST FOR A BELL':'◷ SLOW TIME · COLLECT 3 STARDUST FOR A BELL';document.querySelectorAll('[data-zone]').forEach(el=>{el.classList.toggle('active',+el.dataset.zone===(game.state==='summit'?3:game.biome));el.classList.toggle('visited',+el.dataset.zone<game.biome);});if(game.seen.size)$('discoveryText').textContent=game.seen.size+' pocket '+(game.seen.size===1?'world discovered.':'worlds discovered.')+' There is always another way through.';}
function frame(now){const dt=Math.min((now-last)/1000||0,.05);last=now;clock+=dt;accumulator+=dt;while(accumulator>=1/120){game.step(1/120);accumulator-=1/120;}draw();ui();requestAnimationFrame(frame);}requestAnimationFrame(frame);
function clearInput(){game.input=[false,false];document.querySelectorAll('.touch-controls button').forEach(el=>el.classList.remove('active'));}
function pause(){if(game.state==='playing'){game.state='paused';clearInput();overlay('TAKE A BREATH','The universe<br>can wait.','Your little spirit is right where you left it.','Keep climbing');}else if(game.state==='paused'){game.state='playing';$('overlay').hidden=true;}}
$('playButton').onclick=()=>{if(audio?.state==='suspended')audio.resume();if(game.state==='ready')game.start();else if(game.state==='gameover')game.continueCheckpoint();else if(game.state==='summit')game.continueEndless();else if(game.state==='paused')game.state='playing';$('overlay').hidden=true;};
$('pauseButton').onclick=pause;$('soundButton').onclick=()=>{sound=!sound;if(sound){audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();tone('collect');}$('soundButton').innerHTML='♫ <span>SOUND '+(sound?'ON':'OFF')+'</span>';$('soundButton').setAttribute('aria-label',sound?'Mute sound':'Enable sound');};
const keys=new Map([['ArrowLeft',0],['ArrowRight',1],['a',0],['d',1]]);
window.addEventListener('keydown',e=>{if(keys.has(e.key)){e.preventDefault();game.input[keys.get(e.key)]=true;}if(!e.repeat&&(e.key==='p'||e.key==='Escape'))pause();});
window.addEventListener('keyup',e=>{if(keys.has(e.key))game.input[keys.get(e.key)]=false;});
const pointers=new Map();function syncPointers(){for(let i=0;i<2;i++){game.input[i]=[...pointers.values()].includes(i);$(i?'rightControl':'leftControl').classList.toggle('active',game.input[i]);}}
$('gameFrame').addEventListener('pointerdown',e=>{if(game.state!=='playing'||e.target.closest('.overlay'))return;e.preventDefault();const box=canvas.getBoundingClientRect(),side=e.clientX<box.left+box.width/2?0:1;pointers.set(e.pointerId,side);$('gameFrame').setPointerCapture(e.pointerId);syncPointers();});
for(const event of ['pointerup','pointercancel','lostpointercapture'])$('gameFrame').addEventListener(event,e=>{pointers.delete(e.pointerId);syncPointers();});
window.addEventListener('blur',()=>{pointers.clear();clearInput();if(game.state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.state==='playing')pause();});
