import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../engine.js';
test('a drain costs one bell and preserves the current recovery altitude',()=>{const g=new Game();g.start();g.camera=900;g.ball.y=800;g.step(1/120);assert.equal(g.lives,6);assert.equal(g.camera,900);assert.ok(g.ball.y>900);});
test('seven is the hard life cap and score never grants a life',()=>{const g=new Game();g.gainLife('gift');assert.equal(g.lives,7);assert.equal(g.score,0);g.lives=5;g.addScore(3000);assert.equal(g.lives,5);g.gainLife('gift');assert.equal(g.lives,6);});
test('portal physics are temporary and returning preserves the main world',()=>{const g=new Game();g.start();const objects=g.objects;g.enterRoom(objects.find(o=>o.type==='portal'));assert.equal(g.room.kind,'tide');assert.notEqual(g.objects,objects);g.exitRoom();assert.equal(g.room,null);assert.equal(g.objects,objects);assert.ok(g.ball.vy>0);});
test('possessed cat is freed after two strikes',()=>{const g=new Game();g.start();const cat={type:'cat',x:210,y:300,r:25,hits:0,cool:0};g.objects=[cat];for(let i=0;i<2;i++){cat.cool=0;g.ball={x:210+Math.sin(g.time*1.3+cat.y)*28,y:320,vx:0,vy:-100,r:13,trail:[]};g.step(1/120);}assert.equal(g.freed,1);assert.equal(cat.dead,true);});
test('a pressed flipper gives a strong upward shot on contact',()=>{const g=new Game();g.start();g.objects=[];g.strikeLock=0;g.input[0]=true;g.flips[0]=1;const f=g.flipper(0);g.ball={x:f.x+(f.ex-f.x)*.6,y:f.y+(f.ey-f.y)*.6+16,vx:0,vy:-200,r:13,trail:[]};g.step(1/120);assert.ok(g.ball.vy>800);assert.ok(g.ball.vx>0);});
test('seventh fall ends run; continue uses biome checkpoint',()=>{const g=new Game();g.start();g.checkpoint=1500;g.lives=1;g.loseLife();assert.equal(g.state,'gameover');g.continueCheckpoint();assert.equal(g.lives,7);assert.equal(g.maxHeight,1500);assert.equal(g.state,'playing');});
test('false summit can continue into another universe',()=>{const g=new Game();g.start();g.ball.y=4700;g.step(1/120);assert.equal(g.state,'summit');g.continueEndless();assert.equal(g.cycle,1);assert.equal(g.state,'playing');});
test('paused simulation does not move the orb',()=>{const g=new Game();g.start();g.state='paused';const y=g.ball.y;g.step(.1);assert.equal(g.ball.y,y);});
test('physical portal entry cannot leak the old camera into the pocket room',()=>{const g=new Game();g.start();const p=g.objects.find(o=>o.type==='portal');g.ball.x=p.x;g.ball.y=p.y;g.ball.vy=0;g.step(1/120);assert.ok(g.room);assert.equal(g.camera,0);assert.equal(g.ball.y,146);});
test('collecting a published room objective restores one bell',()=>{const g=new Game();g.start();g.lives=5;g.enterRoom(g.objects.find(o=>o.type==='portal'));g.room.collected=3;g.exitRoom();assert.equal(g.lives,6);});
function playWithTimedTaps(g, seconds=300){for(let i=0;i<120*seconds&&g.state==='playing';i++){g.input=[false,false];for(let side=0;side<2;side++){const f=g.flipper(side),dx=f.ex-f.x,dy=f.ey-f.y,t=Math.max(0,Math.min(1,((g.ball.x-f.x)*dx+(g.ball.y-f.y)*dy)/(dx*dx+dy*dy))),px=f.x+dx*t,py=f.y+dy*t;if(Math.hypot(g.ball.x-px,g.ball.y-py)<29&&g.ball.y>py-12&&g.ball.vy<190)g.input[side]=true;}g.step(1/120);}}
test('held flippers do not replace deliberate timing',()=>{for(const input of [[false,false],[true,true]]){const g=new Game();g.start();for(let i=0;i<120*130&&g.state==='playing';i++){g.input=input;g.step(1/120);}assert.equal(g.state,'gameover');}const g=new Game();g.start();playWithTimedTaps(g);assert.equal(g.state,'summit');});
test('protected side rails guide a falling orb back toward the playfield',()=>{const g=new Game();g.start();g.objects=[];g.ball={x:68,y:130,vx:-80,vy:-200,r:13,trail:[]};g.step(1/120);assert.ok(g.ball.vx>0);assert.ok(g.ball.vy>0);});
test('living currents and mandalas alter the orb trajectory',()=>{const g=new Game();g.start();g.objects=[{type:'flow',x:100,y:100,w:220,h:180,dir:1,strength:280}];g.ball={x:210,y:170,vx:0,vy:0,r:13,trail:[]};g.step(1/120);assert.ok(g.ball.vx>0);g.objects=[{type:'mandala',x:210,y:220,r:34,phase:0,cool:0}];g.ball={x:245,y:220,vx:0,vy:-50,r:13,trail:[]};g.step(1/120);assert.notEqual(g.ball.vx,0);assert.ok(g.ball.vy>400);});
